#!/bin/bash

usage="
Usage:
    $0 [options]

Options:
    -b, --build             build the container before starting
    -c, --create  string    create the container with given name but do not start it
    -e, --execute string    execute the given string as a command in the container
    -p, --project string    run the chosen project
"

usage() {
    echo "$usage"
    exit 1
}

OPTIONS=$(getopt -o bc:e:p: --long build,create:,execute:,project: == "$@")

if [ $? -ne 0 ]; then
    usage
    exit 1
fi

container="lingua-franca-tsn-dev"
build=false
create=""
execute=""
project=""

eval set -- "$OPTIONS"
while true; do
    case "$1" in
        -b|--build)
            build=true
            shift
            ;;
        -c|--create)
            create=$2
            shift 2
            ;;
        -e|--execute)
            execute=$2
            shift 2
            ;;
        -p|--project)
            project=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            usage
            ;;
    esac
done

build() {
    ./build
}

create() {
    name="$1"

    echo "creating lingua-franca-tsn container with name $name"

    podman create \
        -it \
        --device /dev/net/tun:/dev/net/tun \
        --volume /dev/kvm:/dev/kvm \
        --volume /sys/fs/cgroup:/sys/fs/cgroup:rw \
        --group-add keep-groups \
        --cap-add NET_ADMIN \
        --cap-add NET_RAW \
        --cap-add SYS_ADMIN \
        --name $name \
        lingua-franca-tsn \
        bash
}

run() {
    podman run \
        -it \
        --rm \
        --device /dev/net/tun:/dev/net/tun \
        --volume /dev/kvm:/dev/kvm \
        --volume /sys/fs/cgroup:/sys/fs/cgroup:rw \
        --group-add keep-groups \
        --cap-add NET_ADMIN \
        --cap-add NET_RAW \
        --cap-add SYS_ADMIN \
        --name $container \
        lingua-franca-tsn
}

execute() {
    cmd="$1"

    podman run \
        -it \
        --rm \
        --device /dev/net/tun:/dev/net/tun \
        --device /dev/kvm:/dev/kvm \
        --volume /sys/fs/cgroup:/sys/fs/cgroup:rw \
        --group-add keep-groups \
        --cap-add NET_ADMIN \
        --cap-add NET_RAW \
        --cap-add SYS_ADMIN \
        --name $container \
        --entrypoint "/bin/bash" \
        lingua-franca-tsn \
        -c "bash $cmd ; bash"
}

if [ $build = true ]; then
    build
fi

if [ -n "$execute" ]; then
    execute "$execute"
elif [ -n "$project" ]; then
    execute "./run -p $project | tee run.log"
elif [ -n "$create" ]; then
    create "$create"
else
    run
fi
