#!/bin/bash

usage="
Usage:
    $0 [options]

Options:
    -p, --project   the project to run
    -t, --tests     run the project tests
"

usage() {
    echo "$usage"
}

OPTIONS=$(getopt -o p:t --long project:,tests == "$@")

if [ $? -ne 0 ]; then
    usage
    exit 1
fi

project=false
testopt=false

eval set -- "$OPTIONS"
while true; do
    case "$1" in
        -p|--project)
            project=$2
            shift 2
            ;;
        -t|--tests)
            testopt=true
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            usage
            ;;
    esac
done

PS1="inet-$INET_VER:\w\$ "
[ -f "$HOME/omnetpp/setenv" ] && . "$HOME/omnetpp/setenv" -f
[ -f "$HOME/inet4.5/setenv" ] && . "$HOME/inet4.5/setenv" -f

. setenv

generic_run() {
    bash tsn-sim/simulations/$project/build.sh
    tsn-sim/simulations/$project/setup.sh
    if [ $testopt = true ]; then
        bash "tsn-sim/simulations/$project/test.sh"
    else
        tsn-sim/simulations/$project/run.sh
    fi
    tsn-sim/simulations/$project/teardown.sh
}

case "$project" in
    talker_listener)
        generic_run
        ;;
    client_server)
        generic_run
        ;;
    basic_federation)
        generic_run
        ;;
    netns_client_server)
        generic_run
        ;;
    socat_netns)
        generic_run
        ;;
    tsn_talker_listener)
        generic_run
        ;;
    five_host)
        generic_run
        ;;
    *)
        echo "project $project not recognized"
        exit 1
        ;;
esac
