# run `podman build -t lingua-franca --no-cache --pull .` to keep everything on latest

# base on the latest Ubuntu container image
FROM ubuntu:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean

RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    vim \
    && apt-get clean

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    openjdk-17-jre \
    openjdk-17-jdk \
    && apt-get clean

WORKDIR /usr/app/lingua-franca

# copy the project files over to container
COPY ./lingua-franca .

RUN bin/lfc-dev --version

ENTRYPOINT bash

# start with `podman run -it --rm lingua-franca`
